Homework2
kuzanatoliy/node.mentoring.program.2018 pull request #2
Opened 2018-04-28 12:31 UTC by kuzanatoliy

It's not well but work

2018-04-30 13:51 UTC, ghost requested changes

2018-04-30 13:51 UTC, MaksimKavalenkaBY commented on utils/dir-watcher/DirWatcher.js
> +    this.emitter = new Emitter();
You can just extend DirWatcher from Emitter and delete this field (so instead of _this.emitter.emit_ you will call _this.emit_)

2018-04-30 13:51 UTC, MaksimKavalenkaBY commented on utils/dir-watcher/DirWatcher.js
> +  }
Having made this class to be extended from Emitter, you could get rid of **on** and **once** methods.

2018-04-30 13:51 UTC, MaksimKavalenkaBY commented on utils/importer/Importer.js
> +  static createImporter(models, watcher) {
Since this method doesn't implement any special logic, let's delete it. For _Importer_ creation use **new** keyword.

2018-04-30 13:51 UTC, MaksimKavalenkaBY commented on index.js
> +Importer.createImporter(models, watcher);
Create _Importer_ via **new** keyword. Feel free to update eslint rules to bypass **no-new** restriction.

2018-04-30 13:51 UTC, MaksimKavalenkaBY commented on index.js
> +const watcher = DirWatcher.watch('./data', 5000);
Please, update DirWatcher class so it could output info first time on the startup.

2018-04-30 16:11 UTC, ghost requested changes

2018-04-30 16:11 UTC, MaksimKavalenkaBY commented on utils/importer/Importer.js
> +    this.importSync = this.importSync.bind(this);
If you use arrow functions, it is not necessary to bind methods with a lexical scope. Arrow functions make use of lexical scope by default (https://derickbailey.com/2015/09/28/do-es6-arrow-functions-really-solve-this-in-javascript).

2018-04-30 18:21 UTC, kuzanatoliy commented on index.js
> +const watcher = DirWatcher.watch('./data', 5000);
Updated

2018-05-01 00:20 UTC, ghost approved these changes

2018-05-01 00:20 UTC, merged