Homework3 v2
kuzanatoliy/node.mentoring.program.2018 pull request #4
Opened 2018-05-27 23:45 UTC by kuzanatoliy

2018-05-28 21:27 UTC, ghost requested changes

2018-05-28 21:27 UTC, MaksimKavalenkaBY commented on utils/streams/index.mjs
> +    const action = params[firstParam];
It might be like
`const action = params[COMMANDS.ACTION]`
So afterall it won't be necessary to define _paramsKeys_, _firstParam_, _secondParam_

2018-05-28 21:27 UTC, MaksimKavalenkaBY commented on utils/streams/transfers.mjs
> +      data[i] = buffer + data[i];
Should be
`lines[i] = buffer + lines[i];`
The reason is that you operate over _lines_ first (line 41) and only after creating a model it is pushed to _data_ array. So _data_ keeps JSON while _lines_ keeps csv content instead

2018-05-29 07:05 UTC, ghost requested changes

2018-05-29 07:05 UTC, MaksimKavalenkaBY commented on utils/streams/transfers.mjs
> +    if (!buffer) {
One time buffer might be empty. It's better to use boolean flag instead

2018-05-29 08:13 UTC, MaksimKavalenka approved these changes

2018-05-29 08:13 UTC, MaksimKavalenka commented on utils/streams/transfers.mjs
> +    .on('end', () => {
As a side note: through2 has syntax of _through2(body, end)_. So _end_ event can be made as _end function_ and be the second parameter.

2018-05-30 16:02 UTC, merged