Homework6
kuzanatoliy/node.mentoring.program.2018 pull request #7
Opened 2018-06-24 20:07 UTC by kuzanatoliy

2018-06-25 23:24 UTC, ghost requested changes

2018-06-25 23:24 UTC, ghost commented on routers/api/auth.mjs
> +    req.body.password = encoding(password);
It throws me an error when trying to encrypt a password. Does this work good for you?

2018-06-25 23:24 UTC, ghost commented on routers/api/auth.mjs
> +    sendJsonData(res, { userInfo }, 200, 'Ok', token);
There is a missmatch between amount of arguments. Actually this methor gets the only 4 of them. 'Ok' is unnecessary since it is hardcoded in _sendJsonData_

2018-06-25 23:24 UTC, ghost commented on routers/api/auth.mjs
> +    sendJsonData(res, { userInfo }, 200, 'Ok', token);
As well as for _loginTreatment_ ('Ok' is unnecessary)

2018-06-25 23:24 UTC, ghost commented on routers/api/auth.mjs
> +    const userInfo = await getUser(req.body);
getUser takes id as a parameter

2018-06-25 23:24 UTC, ghost commented on routers/api/products.mjs
> +    const product = await createProduct(req.product);
To update some product, a user has to pass an ID. _createProduct_ doesn't take it into consideration. So we'll end up creating a new product instead of updating

2018-06-25 23:34 UTC, MaksimKavalenkaBY commented
In addition to the requested changes above:
1. Let's follow up on the task criteria. So please make use of postgresql.
2. I might skip it occasionally but I didn't fount implementation for the 7th item.

2018-06-26 05:59 UTC, kuzanatoliy commented on routers/api/auth.mjs
> +    sendJsonData(res, { userInfo }, 200, 'Ok', token);
done

2018-06-26 05:59 UTC, kuzanatoliy commented on routers/api/auth.mjs
> +    sendJsonData(res, { userInfo }, 200, 'Ok', token);
done

2018-06-26 05:59 UTC, kuzanatoliy commented on routers/api/auth.mjs
> +    const userInfo = await getUser(req.body);
done

2018-06-26 06:00 UTC, kuzanatoliy commented on routers/api/products.mjs
> +    const product = await createProduct(req.product);
done

2018-06-28 22:49 UTC, ghost requested changes

2018-06-28 22:49 UTC, MaksimKavalenkaBY commented on controllers/review.mjs
> +  attributes: ['id', 'email', 'firstName', 'lastName'],
In order to conjunсt a root object (e.g. review) with some metadata (e.g. user info), you need to add alias to be the third attribute of USER_INCLUDE_CONFIG
`as: 'user'`

2018-06-28 22:49 UTC, MaksimKavalenkaBY commented on bin/import/index.mjs
> +  if (model) {
Viceversa -> **!model**

2018-06-28 22:49 UTC, MaksimKavalenkaBY commented on bin/import/index.mjs
> +  if (file) {
Viceversa -> **!file**

2018-06-28 22:49 UTC, MaksimKavalenkaBY commented on bin/import/index.mjs
> +  if (prepareParams) {
Viceversa -> **!prepareParams**

2018-06-29 05:02 UTC, kuzanatoliy commented on controllers/review.mjs
> +  attributes: ['id', 'email', 'firstName', 'lastName'],
done

2018-06-29 05:02 UTC, kuzanatoliy commented on bin/import/index.mjs
> +  if (model) {
done

2018-06-29 05:03 UTC, kuzanatoliy commented on bin/import/index.mjs
> +  if (file) {
done

2018-06-29 05:03 UTC, kuzanatoliy commented on bin/import/index.mjs
> +  if (prepareParams) {
done

2018-06-29 07:39 UTC, ghost approved these changes

2018-06-29 07:49 UTC, merged